{
 "title": "MQ CloudWatch",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "MQ AWS CloudWatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MQGET: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.0" },
     "metricName": "queue.mqget_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQGET: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.1" },
     "metricName": "queue.mqget_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQGET: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.2" },
     "metricName": "queue.mqget_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQGET: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.3" },
     "metricName": "queue.mqget_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQGET: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.4" },
     "metricName": "queue.mqget_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQPUT: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.0" },
     "metricName": "queue.mqput_mqput1_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQPUT: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.1" },
     "metricName": "queue.mqput_mqput1_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQPUT: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.2" },
     "metricName": "queue.mqput_mqput1_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQPUT: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.3" },
     "metricName": "queue.mqput_mqput1_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "MQPUT: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.4" },
     "metricName": "queue.mqput_mqput1_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Depth: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.0" },
     "metricName": "queue.queue_depth",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Depth: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.1" },
     "metricName": "queue.queue_depth",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Depth: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.2" },
     "metricName": "queue.queue_depth",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Depth: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.3" },
     "metricName": "queue.queue_depth",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Depth: {{queue}}",
     "dimensions": { "qmgr": "QM1", "queue": "APP.4" },
     "metricName": "queue.queue_depth",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System CPU",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.system_cpu_time_percentage",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "User CPU",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.user_cpu_time_percentage",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Log write latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.log_write_latency_seconds",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "QMgr file system - in use [{{qmgr}}]",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.log_file_system_in_use_bytes",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Log file system - in use [{{qmgr}}]",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.queue_manager_file_system_in_use_bytes",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ND Sub - low-water",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.non_durable_subscriber_low_water_mark",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "alias": "ND Sub - high-water",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.non_durable_subscriber_high_water_mark",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "alias": "ND MQSUB Calls",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.create_non_durable_subscription_count",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Persistent Bytes Put",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Persistent Bytes",
     "dimensions": { "qmgr": "QM1" },
     "metricName": "qmgr.put_persistent_messages_bytes",
     "namespace": "IBM/MQ",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}