{
 "title": "MQ InfluxDB",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col: $tag_queue",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue",
     "query": "SELECT sum(\"mqget\") as MQGET  FROM \"queue\" WHERE \"queue\" =~ /APP.*/ AND $timeFilter GROUP BY time(10s), \"queue\" fill(null)",
     "select": [
      [
       { "params": [ "mqget_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "MQGET" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=~", "value": "/APP.*/" }
     ]
    },
    {
     "alias": "$col: $tag_queue",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue",
     "query": "SELECT sum(\"mqput_mqput1\") as MQPUT FROM \"queue\" WHERE \"queue\" =~ /APP.*/ AND $timeFilter GROUP BY time(10s), \"queue\" fill(null)",
     "select": [
      [
       { "params": [ "mqput_mqput1_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "MQPUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=~", "value": "/APP.*/" }
     ]
    },
    {
     "alias": "$col: $tag_queue",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue",
     "query": "SELECT median(\"queue_depth\") as DEPTH FROM \"queue\" WHERE \"queue\" =~ /APP.*/ AND $timeFilter GROUP BY time(10s), \"queue\" fill(null)",
     "select": [
      [
       { "params": [ "queue_depth" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Depth" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=~", "value": "/APP.*/" }
     ]
    },
    {
     "alias": "$col: $tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "queue",
     "query": "SELECT median(\"queue_depth\") as DEPTH FROM \"queue\" WHERE \"queue\" =~ /APP.*/ AND $timeFilter GROUP BY time(10s), \"queue\" fill(null)",
     "select": [
      [
       { "params": [ "oldest_message_age" ], "type": "field" },
       { "params": [ "Oldest" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=~", "value": "/APP.*/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System CPU%",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       { "params": [ "system_cpu_time_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "User CPU%",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       { "params": [ "user_cpu_time_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log write latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       { "params": [ "log_write_latency_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "QMgr file system - in use [$tag_qmgr]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "qmgr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       {
        "params": [
         "queue_manager_file_system_in_use_bytes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Log file system  - in use [$tag_qmgr]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "qmgr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       { "params": [ "log_file_system_in_use_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       {
        "params": [
         "non_durable_subscriber_low_water_mark"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ND - Low Water" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "non_durable_subscriber_high_water_mark"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ND - High Water" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "create_non_durable_subscription_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "ND MQSUB calls" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "connname" ], "type": "tag" },
      { "params": [ "qmgr" ], "type": "tag" },
      { "params": [ "rqmname" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "channel",
     "select": [
      [
       { "params": [ "status_squash" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Persistent Bytes Put",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qmgr",
     "select": [
      [
       { "params": [ "put_persistent_messages_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}