{
 "title": "MQ OpenTSDB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "MQ OpenTSDB Capture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "last",
     "alias": "MQGET: [[tag_queue]]",
     "currentFilterKey": "queue",
     "currentFilterType": "wildcard",
     "currentFilterValue": "APP.*",
     "currentTagKey": "queue",
     "currentTagValue": "APP.0",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.queue.mqget_count"
    },
    {
     "aggregator": "last",
     "alias": "MQPUT: [[tag_queue]]",
     "currentFilterKey": "queue",
     "currentFilterType": "wildcard",
     "currentFilterValue": "APP.*",
     "currentTagKey": "object",
     "currentTagValue": "APP.0",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.queue.mqput_mqput1_count"
    },
    {
     "aggregator": "last",
     "alias": "Depth: [[tag_queue]]",
     "currentFilterKey": "queue",
     "currentFilterType": "wildcard",
     "currentFilterValue": "APP.*",
     "currentTagKey": "object",
     "currentTagValue": "APP.0",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.queue.queue_depth"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "System CPU%",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.system_cpu_time_percentage"
    },
    {
     "aggregator": "avg",
     "alias": "User CPU%",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.user_cpu_time_percentage"
    }
   ]
  },
  {
   "title": "Log write latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Latency",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.log_write_latency_seconds"
    }
   ]
  },
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "QMgr file system - in use [$tag_qmgr]",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.queue_manager_file_system_in_use_bytes"
    },
    {
     "aggregator": "sum",
     "alias": "Log file system - in use [$tag_qmgr]",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.log_file_system_in_use_bytes"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "ND Sub - low-water",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.non_durable_subscriber_low_water_mark"
    },
    {
     "aggregator": "avg",
     "alias": "ND Sub - high-water",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.non_durable_subscriber_high_water_mark"
    },
    {
     "aggregator": "sum",
     "alias": "ND MQSUB calls",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.create_non_durable_subscription_count"
    }
   ]
  },
  {
   "title": "Persistent Bytes Put",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Persistent bytes PUT",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "ibmmq.qmgr.put_persistent_messages_bytes"
    }
   ]
  }
 ]
}