{
 "title": "Channel Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ibmmq_channel_status_squash+0" },
    { "expr": "ibmmq_channel_status+0" }
   ]
  },
  {
   "title": "Channel Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "ibmmq_channel_time_since_msg", "legendFormat": "{{channel}} [{{type}}]" }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_channel_messages{type!=\"SVRCONN\"}",
     "legendFormat": "{{channel}} [{{type}}]"
    }
   ]
  },
  {
   "title": "Network Transfer Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "ibmmq_channel_nettime_short", "legendFormat": "Short: {{channel}}" },
    { "expr": "ibmmq_channel_nettime_long", "legendFormat": "Long: {{channel}}" }
   ]
  },
  {
   "title": "Channel Batches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_channel_batches{type!=\"SVRCONN\"}",
     "legendFormat": "Batches: {{channel}}"
    },
    { "expr": "ibmmq_channel_batchsz_short", "legendFormat": "BatchSz (short): {{channel}}" },
    { "expr": "ibmmq_channel_batchsz_long", "legendFormat": "BatchSz (long): {{channel}}" }
   ]
  },
  {
   "title": "Transmission Queue Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{type=\"SENDER\"}",
     "legendFormat": "Short: {{channel}}"
    },
    {
     "expr": "ibmmq_channel_xmitq_time_long{type=\"SENDER\"}",
     "legendFormat": "Long: {{channel}}"
    }
   ]
  }
 ]
}