{
 "title": "Logging",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ibmmq_qmgr_status+0" },
    {
     "expr": "ibmmq_qmgr_log_extent_current+0"
    },
    {
     "expr": "ibmmq_qmgr_log_extent_restart+0"
    }
   ]
  },
  {
   "title": "NHA Sync Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ibmmq_nha_synchronous_log_sent_bytes",
     "legendFormat": "{{qmgr}}:{{nhainstance}}"
    }
   ]
  },
  {
   "title": "NHA Backlog Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "ibmmq_nha_backlog_average_bytes",
     "legendFormat": "{{qmgr}}:{{nhainstance}}"
    }
   ]
  }
 ]
}