{
 "title": "MQ Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_mqget_count{queue=~\"APP.*\"} ",
     "legendFormat": "Get: {{queue}}"
    },
    {
     "expr": "ibmmq_queue_mqput_mqput1_count{queue=~\"APP.*\"}",
     "legendFormat": "Put: {{queue}}"
    },
    {
     "expr": "ibmmq_queue_queue_depth_count{queue=~\"APP.*\"}",
     "legendFormat": "Depth: {{queue}}"
    },
    {
     "expr": "ibmmq_queue_oldest_message_age_count{queue=~\"APP.*\"}",
     "legendFormat": "Oldest msg {{queue}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_qmgr_published_to_subscribers_message_count",
     "legendFormat": "Publications: {{qmgr}}"
    },
    {
     "expr": "ibmmq_qmgr_interval_mqput_mqput1_total_count",
     "legendFormat": "Put: {{qmgr}}"
    },
    {
     "expr": "ibmmq_qmgr_interval_destructive_get_total_count",
     "legendFormat": "Get: {{qmgr}}"
    },
    {
     "expr": "ibmmq_qmgr_persistent_message_browse_count + ibmmq_qmgr_non_persistent_message_browse_count",
     "legendFormat": "Browse {{ qmgr}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ibmmq_qmgr_system_cpu_time_percentage",
     "legendFormat": "System CPU%: {{platform}}"
    },
    {
     "expr": "ibmmq_qmgr_user_cpu_time_percentage",
     "legendFormat": "User CPU%: {{platform}}"
    }
   ]
  },
  {
   "title": "Log write latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_write_latency_seconds",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ibmmq_qmgr_queue_manager_file_system_in_use_bytes",
     "legendFormat": "QMgr file system - in use [{{qmgr}}/{{platform}}]"
    },
    {
     "expr": "ibmmq_qmgr_log_file_system_in_use_bytes",
     "legendFormat": "Log file system - in use [{{qmgr}}/{{platform}}]"
    },
    {
     "expr": "ibmmq_qmgr_mq_errors_file_system_free_space_percentage",
     "legendFormat": "File system usage %"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_qmgr_non_durable_subscriber_low_water_mark",
     "legendFormat": "ND Sub - low-water"
    },
    {
     "expr": "ibmmq_qmgr_non_durable_subscriber_high_water_mark",
     "legendFormat": "ND Sub - high-water"
    },
    {
     "expr": "ibmmq_qmgr_create_non_durable_subscription",
     "legendFormat": "ND MQSUB calls"
    }
   ]
  },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 14 },
   "targets": [
    { "expr": "ibmmq_channel_status_squash+0" },
    { "expr": "ibmmq_channel_status+0" }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_channel_messages{type!=\"SVRCONN\"}",
     "legendFormat": "{{channel}} [{{type}}]"
    }
   ]
  },
  {
   "title": "Persistent Bytes Put",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_put_persistent_messages_bytes)",
     "legendFormat": "Persistent bytes PUT"
    }
   ]
  }
 ]
}