{
 "title": "Queue Manager Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ibmmq_qmgr_status+0" },
    {
     "expr": "ibmmq_qmgr_channel_initiator_status+0"
    },
    {
     "expr": "ibmmq_qmgr_command_server_status+0"
    },
    { "expr": "ibmmq_qmgr_uptime" },
    { "expr": "ibmmq_qmgr_connection_count+0" },
    { "expr": "ibmmq_qmgr_max_channels+0" },
    {
     "expr": "ibmmq_qmgr_max_active_channels+0"
    }
   ]
  },
  {
   "title": "Connection Count (inc. internal processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_qmgr_connection_count", "legendFormat": "Connection Count: {{qmgr}}" }
   ]
  },
  {
   "title": "Processed Publications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_exporter_publications",
     "legendFormat": "{{qmgr}}"
    }
   ]
  },
  {
   "title": "FDC Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ibmmq_qmgr_mq_fdc_file_count" }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 13 },
   "targets": [
    { "expr": "ibmmq_cluster_suspend", "legendFormat": "State" }
   ]
  }
 ]
}