{
 "title": "Queue Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Message Lifetime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_qtime_short",
     "legendFormat": "QTime Short: {{queue}}@{{qmgr}}"
    },
    { "expr": "ibmmq_queue_qtime_long", "legendFormat": "QTime Long: {{queue}}@{{qmgr}}" }
   ]
  },
  {
   "title": "Oldest message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_oldest_message_age", "legendFormat": "Oldest msg: {{queue}}@{{qmgr}}" },
    {
     "expr": "max(ibmmq_queue_oldest_message_age)",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Put/Get Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_time_since_get", "legendFormat": "Since Get: {{queue}}@{{qmgr}}" },
    { "expr": "ibmmq_queue_time_since_put", "legendFormat": "Since Put: {{queue}}@{{qmgr}}" }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_depth", "legendFormat": "Depth: {{queue}}@{{qmgr}}" },
    {
     "expr": "(100 * ibmmq_queue_depth) / ibmmq_queue_attribute_max_depth",
     "legendFormat": "% Depth: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Object handles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_input_handles", "legendFormat": "IPPROCS: {{queue}}@{{qmgr}}" },
    { "expr": "ibmmq_queue_output_handles", "legendFormat": "OPPROCS: {{queue}}@{{qmgr}}" }
   ]
  }
 ]
}