{
 "title": "Topic Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Topic Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_topic_messages_published{type=\"pub\"}",
     "legendFormat": "Messages (Sub): {{qmgr}} {{topic}}"
    },
    {
     "expr": "ibmmq_topic_messages_received{type=\"sub\"}",
     "legendFormat": "Published Messages: {{qmgr}} {{topic}}"
    },
    {
     "expr": "ibmmq_qmgr_topic_mqput_mqput1_interval_total",
     "legendFormat": "Total publications: {{qmgr}}"
    }
   ]
  },
  {
   "title": "Publishers and Subscribers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_topic_publisher_count", "legendFormat": "Publisher: {{topic}}" },
    { "expr": "ibmmq_topic_subscriber_count", "legendFormat": "Subscribers: {{topic}}" }
   ]
  },
  {
   "title": "Last message",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ibmmq_topic_time_since_msg_published",
     "legendFormat": "Publications"
    },
    {
     "expr": "ibmmq_topic_time_since_msg_received",
     "legendFormat": "Subscriptions"
    }
   ]
  }
 ]
}