{
 "title": "z/OS status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_depth{platform=\"ZOS\"}",
     "legendFormat": "{{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ibmmq_channel_status_squash{platform=\"ZOS\"}+0"
    },
    {
     "expr": "ibmmq_channel_status{platform=\"ZOS\"}+0"
    }
   ]
  },
  {
   "title": "Oldest Message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_oldest_message_age{platform=\"ZOS\"}",
     "legendFormat": "{{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ibmmq_channel_messages{platform=\"ZOS\", channel=\"SYSTEM.ADMIN.SVRCONN\"})",
     "legendFormat": "Total: SYSTEM.ADMIN.SVRCONN"
    },
    {
     "expr": "(ibmmq_channel_messages{platform=\"ZOS\", channel=\"SYSTEM.ADMIN.SVRCONN\"})",
     "legendFormat": "SYSTEM.ADMIN.SVRCONN: {{connname}} {{qmgr}}"
    },
    {
     "expr": "ibmmq_channel_messages{type !='SVRCONN', platform=\"ZOS\"}",
     "legendFormat": "Channel: {{channel}}"
    }
   ]
  }
 ]
}