{
 "title": "z/OS status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Queue Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_mqget_count{queue=~\"APP.*\",platform=\"ZOS\"} ",
     "legendFormat": "Get: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_mqput_mqput1_count{queue=~\"APP.*\",platform=\"ZOS\"} ",
     "legendFormat": "Put: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_hi_depth{queue=~\"APP.*\",platform=\"ZOS\"} ",
     "legendFormat": "Max Depth: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "(100 * ibmmq_queue_depth{platform=\"ZOS\"})/ibmmq_queue_attribute_max_depth",
     "legendFormat": "% Full: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ibmmq_channel_status_squash{platform=\"ZOS\"}+0"
    },
    {
     "expr": "ibmmq_channel_status{platform=\"ZOS\"}+0"
    }
   ]
  },
  {
   "title": "Message Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s", "label": "Oldest Msg" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_oldest_message_age{platform=\"ZOS\"}",
     "legendFormat": "{{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_time_since_get{platform=\"ZOS\"}",
     "legendFormat": "Since Get: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_time_since_put{platform=\"ZOS\"}",
     "legendFormat": "Since Put: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ibmmq_channel_messages{platform=\"ZOS\", channel=\"SYSTEM.ADMIN.SVRCONN\"})",
     "legendFormat": "Total: SYSTEM.ADMIN.SVRCONN"
    },
    {
     "expr": "(ibmmq_channel_messages{platform=\"ZOS\", channel=\"SYSTEM.ADMIN.SVRCONN\"})",
     "legendFormat": "SYSTEM.ADMIN.SVRCONN: {{connname}} {{qmgr}} {{jobname}}"
    },
    {
     "expr": "ibmmq_channel_messages{type !='SVRCONN', platform=\"ZOS\"}",
     "legendFormat": "Channel: {{channel}}"
    }
   ]
  },
  {
   "title": "Unique Channels",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "expr": "count(count_over_time(ibmmq_channel_messages{platform=\"ZOS\"}[30m])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Unique Channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count_over_time(ibmmq_channel_messages{platform=\"ZOS\"}[30m]))",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Bufferpool Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-ibmmq_bufferpool_buffers_free_percent",
     "legendFormat": "Used%: BP {{bufferpool}}"
    }
   ]
  },
  {
   "title": "Pageset Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*((ibmmq_pageset_pages_total - ibmmq_pageset_pages_unused)/ibmmq_pageset_pages_total)",
     "legendFormat": "Used %: PS {{pageset}} BP: {{bufferpool}}"
    },
    {}
   ]
  },
  {
   "title": "BP/PS Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "100*((ibmmq_pageset_pages_total - ibmmq_pageset_pages_unused)/ibmmq_pageset_pages_total)",
     "legendFormat": "Pageset Usage"
    },
    {
     "expr": "100-ibmmq_bufferpool_buffers_free_percent"
    }
   ]
  }
 ]
}