# This script takes the output from running the collector for a short time and extracting
# the names of all the metrics

cat << EOF
# This file is referenced from the global TypesDB attribute in
# /etc/collectd.conf. It does not need to be copied into the default
# types.db file, but can be named independently. For example
#
#     TypesDB "/usr/share/collectd/types.db" "<directory>/mqtypes.db"
#
# All of the currently-known metrics generated by MQ are listed here
# as gauges with no specific maximum value.

EOF

inputFile="/tmp/m.out"
cat $inputFile | cut -d/ -f3 |\
                 cut -d- -f1 |\
                 egrep ^[a-z] |\
                 grep _ |\
                 sort -u|\
                 awk '{printf("%-64.64s  value:GAUGE:0:U\n",$1)}' 
